package lgrab;


import javax.swing.JOptionPane;
import javax.swing.BorderFactory;
import java.awt.Font;
import javax.swing.JTextArea;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import javax.swing.SwingWorker;
import static javax.swing.UIManager.*;
/**
 *
 * @author adityatj
 */
public class MLG extends javax.swing.JFrame {

    public String lyricsSite = "http://www.darklyrics.com/";
    public BufferedReader in;
    public URL url;
    public URLConnection urlCon;
    public String artistName = "";
    public String songName = "";
    public JTextArea txtArea;

    /** Creates new form MLG */
    public MLG() {
        try
        {
            setLookAndFeel ("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            txtArea  = new JTextArea();
        txtArea.setFont( new java.awt.Font("Segoe UI", 0, 12));
        txtArea.setOpaque(false);
        txtArea.setEditable(false);
        }
        catch(Exception e)
        {
            System.err.println(e);
        }
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jMenu1 = new javax.swing.JMenu();
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jMenu2 = new javax.swing.JMenu();
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 12));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MetalLyrics v0.2 by whizz");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Artist :");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Song :");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton1.setText("Get Lyrics!");
        jButton1.setMaximumSize(new java.awt.Dimension(87, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jEditorPane1);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");

        jMenuItem2.setText("Instructions");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("About Me !");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (jTextField1.getText().equals("") || jTextField2.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Blank artist or song name !", "Error !", javax.swing.JOptionPane.DEFAULT_OPTION);
        } else {
            jTextField1.setEnabled(false);
            jTextField2.setEnabled(false);
            new LyricsWorker().execute();
        }
    }                                        

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try {
            if(in != null)
                in.close();
        } catch (IOException ex) {
            //none
        }
        System.exit(1);
    }                                          

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                           


        txtArea.setText("Enter the artist and song name.\nClick Get Lyrics !\nNOTE: Be specific upon song's name and artist's name.");
        JOptionPane.showMessageDialog(null, txtArea,  "Instructions...", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    }                                          

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        txtArea.setText("I'm whizz , a freelance coder.\nI made this app under GNU/GPL license so feel free to distribute it! :)");
        javax.swing.JOptionPane.showMessageDialog(null, txtArea, "About me...", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MLG().setVisible(true);
            }
        });
    }

    class LyricsWorker extends SwingWorker<Integer, Integer> {

        @Override
        protected Integer doInBackground() throws Exception {
            jEditorPane1.setContentType("text/html");
            jEditorPane1.setEditable(false);
            jEditorPane1.setText("<p style=\"font-family:Courier New;\">Getting Lyrics...</p>");
            try {
                artistName = jTextField1.getText().toLowerCase().replaceAll("\\s+$", "");
                songName = jTextField2.getText().toLowerCase().replaceAll("\\s+$", "");
                String str, intSongURL = "", inter = "", finalSong = "<p style=\"font-family:Courier New;\">", artistURL = "";
                artistURL = lyricsSite + artistName.charAt(0) + "/" + artistName.replaceAll(" ", "") + ".html";
                url = new URL(artistURL);
                urlCon = url.openConnection();
                in = new BufferedReader(new InputStreamReader(urlCon.getInputStream()));

                while ((str = in.readLine()) != null) {
                    if (str.toLowerCase().replaceAll("\\<.*?>", "").equals(songName)) {
                        intSongURL = str;
                        break;
                    }
                }
                String songURL = lyricsSite + intSongURL.substring(11, intSongURL.indexOf("\"", 16));
                try {
                    int test = Integer.parseInt("" + songURL.charAt(songURL.length() - 2));
                    inter = "<h3><a name=\"" + songURL.charAt(songURL.length() - 2) + songURL.charAt(songURL.length() - 1) + "\">";
                } catch (Exception ee) {
                    inter = "<h3><a name=\"" + songURL.charAt(songURL.length() - 1) + "\">";
                }
                url = new URL(songURL);
                urlCon = url.openConnection();
                in = new BufferedReader(new InputStreamReader(urlCon.getInputStream()));
                while ((str = in.readLine()) != null) {
                    if (str.contains(inter)) {
                        //finalSong = str.replaceAll("\\<.*?>","").substring(3) + "\n\n";
                        while ((str = in.readLine()) != null) {
                            if (str.contains("name=\"") || str.contains("class=\"thanks\"")) {
                                break;
                            } else {
                                finalSong = finalSong + str;
                            }
                        }
                    }
                }
                //finalSong = finalSong.replaceAll("\\<.*?>","");
                jEditorPane1.setText(finalSong + "</p>");
                jTextField1.setEnabled(true);
                jTextField2.setEnabled(true);
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, "May be a connection problem or the requird lyrics aren't found.\nI patch'em up in the next version. :)", "Error !", javax.swing.JOptionPane.DEFAULT_OPTION);
                jTextField1.setEnabled(true);
                jTextField2.setEnabled(true);
                jEditorPane1.setText("");
                in.close();
            }
            return 1;
        }
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration                   
}
